## Importing Libraries

In [1]:
import torch
import numpy as np

In [2]:
### Checking GPU
torch.cuda.is_available()

True

## Initializing a Tensor

In [6]:
##Directly from data : List of List
data  = [[1,2], [3,4]]
data_tensor = torch.tensor(data)
data_tensor

tensor([[1, 2],
        [3, 4]])

In [7]:
## From a bumpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
## This also works~
torch.tensor(np_array)

tensor([[1, 2],
        [3, 4]])

In [12]:
## from other tensors
x_ones = torch.ones(10,20, dtype=int)
x_ones

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
## Convert to float
x_ones_float = x_ones.float()
x_ones_float

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])

## Some useful functions

In [22]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[4.5451e-01, 3.6973e-01, 8.6639e-01],
        [7.0458e-01, 2.2525e-04, 9.3841e-01]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a tensor

In [34]:
print(f"Shape of tensor : {rand_tensor.shape}")
print(f"Number of dimension of tensor : {rand_tensor.dim}")
print(f"Type of tensor : {rand_tensor.dtype}")
print(f"Device tensor is stored on : {rand_tensor.device}")

Shape of tensor : torch.Size([2, 3])
Number of dimension of tensor : <built-in method dim of Tensor object at 0x7fb382d05b80>
Type of tensor : torch.float32
Device tensor is stored on : cpu


## Moving Tensor from cpu to GPU

In [35]:
rand_tensor.to("cuda")

tensor([[4.5451e-01, 3.6973e-01, 8.6639e-01],
        [7.0458e-01, 2.2525e-04, 9.3841e-01]], device='cuda:0')

## Slicing and Dicing

In [37]:
ex_tensor = torch.rand(3,4)
ex_tensor

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

In [38]:
ex_tensor[:,:3]

tensor([[0.0957, 0.4206, 0.5921],
        [0.1756, 0.0835, 0.7985],
        [0.9688, 0.7642, 0.4301]])

In [39]:
ex_tensor[:,2:3]

tensor([[0.5921],
        [0.7985],
        [0.4301]])

In [40]:
ex_tensor[:,-1]

tensor([0.2761, 0.6379, 0.8843])

## Joining Tensors : Concatenation

In [42]:
torch.cat([ex_tensor, ex_tensor])

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843],
        [0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

In [45]:
torch.cat([ex_tensor, ex_tensor], axis=0)

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843],
        [0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

In [43]:
torch.cat([ex_tensor, ex_tensor], axis=1)

tensor([[0.0957, 0.4206, 0.5921, 0.2761, 0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379, 0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843, 0.9688, 0.7642, 0.4301, 0.8843]])

In [44]:
torch.cat([ex_tensor, ex_tensor], dim=1)

tensor([[0.0957, 0.4206, 0.5921, 0.2761, 0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379, 0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843, 0.9688, 0.7642, 0.4301, 0.8843]])

## Arithmentic on Tensor

In [46]:
ex_tensor

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

### Broadcast Addition

In [48]:
ex_tensor + 1

tensor([[1.0957, 1.4206, 1.5921, 1.2761],
        [1.1756, 1.0835, 1.7985, 1.6379],
        [1.9688, 1.7642, 1.4301, 1.8843]])

In [51]:
ex2_tensor = torch.rand(1,4)
ex2_tensor

tensor([[0.5904, 0.1807, 0.4640, 0.7732]])

In [52]:
ex_tensor + ex2_tensor

tensor([[0.6861, 0.6013, 1.0560, 1.0493],
        [0.7660, 0.2642, 1.2624, 1.4111],
        [1.5592, 0.9449, 0.8940, 1.6575]])

### Matrix Multiplication

In [53]:
## Ex Tensor for shape 3,4 and ex2 tensor of 1x4 => Transposed 4x1 results in 3x1 matrix
ex_tensor @ ex2_tensor.T

tensor([[0.6207],
        [0.9824],
        [1.5934]])

In [55]:
## Ex Tensor for shape 3,4 and ex2 tensor of 1x4 => Transposed 4x1 results in 3x1 matrix
torch.matmul(ex_tensor, ex2_tensor.T)

tensor([[0.6207],
        [0.9824],
        [1.5934]])

In [56]:
## Ex Tensor for shape 3,4 and ex2 tensor of 1x4 => Transposed 4x1 results in 3x1 matrix
ex_tensor.matmul(ex2_tensor.T)

tensor([[0.6207],
        [0.9824],
        [1.5934]])

### Element wise Multiplication

In [60]:
ex_tensor

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

In [61]:
ex_tensor.mul(ex_tensor)

tensor([[0.0092, 0.1769, 0.3506, 0.0762],
        [0.0308, 0.0070, 0.6376, 0.4069],
        [0.9386, 0.5840, 0.1850, 0.7821]])

In [62]:
ex_tensor * ex_tensor

tensor([[0.0092, 0.1769, 0.3506, 0.0762],
        [0.0308, 0.0070, 0.6376, 0.4069],
        [0.9386, 0.5840, 0.1850, 0.7821]])

### Suming it up

In [64]:
ex_tensor

tensor([[0.0957, 0.4206, 0.5921, 0.2761],
        [0.1756, 0.0835, 0.7985, 0.6379],
        [0.9688, 0.7642, 0.4301, 0.8843]])

In [67]:
print(f"All up sum {ex_tensor.sum()}")
print(f"Column wise sum {ex_tensor.sum(0)}")
print(f"Row wise sum {ex_tensor.sum(1)}")

All up sum 6.1273417472839355
Column wise sum tensor([1.2401, 1.2682, 1.8207, 1.7983])
Row wise sum tensor([1.3844, 1.6954, 3.0475])
