## Importing Library

In [1]:
import torch
import numpy

## Exploring Autograd

Autograd is needed to calculate gradient in back propogation of any neural network. Autograd is automatic differentiation engine in Pytorch

In [2]:
# requires_grad setting to True means we need to compute gradient after every operation its been used in
a = torch.tensor([5.], requires_grad=True)
b= torch.tensor([6.], requires_grad=True)

In [5]:
a

tensor([5.], requires_grad=True)

In [6]:
b

tensor([6.], requires_grad=True)

In [7]:
y = a**3 - b**2
y

tensor([89.], grad_fn=<SubBackward0>)

Suppose y is loss. We need to calculate 
- dy/da => 3*(a**2) => 75
- dy/db => -2*b => -12

Using Autograd we can compute it auomatically

In [8]:
a.grad 

Its none in the beginning.

In [9]:
y.backward()

In [10]:
a.grad

tensor([75.])

In [11]:
b.grad

tensor([-12.])

## Example

In [12]:
W = torch.randn(10,1, requires_grad=True)
b = torch.randn(1, requires_grad = True)
W,b

(tensor([[-0.4472],
         [ 0.2763],
         [-1.2931],
         [ 0.4786],
         [-2.3143],
         [-0.3986],
         [ 0.5176],
         [ 1.4266],
         [-1.8022],
         [-0.4652]], requires_grad=True),
 tensor([-1.2512], requires_grad=True))

In [14]:
x = torch.randn(1,10)
x

tensor([[-1.9973, -0.5639,  1.4689,  0.0625, -0.1191, -0.2536, -0.4693, -0.2688,
         -1.9155,  0.0652]])

In [15]:
output = torch.matmul(x, W) + b
output

tensor([[0.7885]], grad_fn=<AddBackward0>)

In [16]:
loss = 1 - output

In [17]:
loss.backward()

In [19]:
W.grad, b.grad

(tensor([[ 1.9973],
         [ 0.5639],
         [-1.4689],
         [-0.0625],
         [ 0.1191],
         [ 0.2536],
         [ 0.4693],
         [ 0.2688],
         [ 1.9155],
         [-0.0652]]),
 tensor([-1.]))

Now we can update the weights!

In [20]:
# torch.no_grad is a way of telling torch to not compute gradients for this operation~
with torch.no_grad(): 
    W -= 0.001 * W.grad.data
    b -= 0.001 * b.grad.data

In [22]:
# Updated weights and bias
W, b

(tensor([[-0.4492],
         [ 0.2757],
         [-1.2917],
         [ 0.4787],
         [-2.3144],
         [-0.3988],
         [ 0.5171],
         [ 1.4263],
         [-1.8041],
         [-0.4651]], requires_grad=True),
 tensor([-1.2502], requires_grad=True))