## Import library

In [1]:
import torch
import torch.nn as nn

## Module

In [2]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(128, 32)
        self.layer2 = nn.Linear(32, 16)
        self.layer3 = nn.Linear(16, 1)
    
    def forward(self, features):
        # x=> (32,128) ; 32 is batch size
        x = self.layer1(features) # (32, 32)
        x = self.layer2(x) # (32, 16)
        x = self.layer3(x) # (32, 1)
        return x

In [3]:
model = Model()
features = torch.randn(2, 128)

In [5]:
model(features)

tensor([[-0.0901],
        [-0.2833]], grad_fn=<AddmmBackward>)

In [7]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

tensor([[-0.2082],
        [-0.1852]], device='cuda:0', grad_fn=<AddmmBackward>)

## Sequential

In [9]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.base = nn.Sequential(
            nn.Linear(128, 32),
            nn.Linear(32, 16),
            nn.Linear(16, 1)
        )  
    def forward(self, features):
        x = self.base(features) 
        return x

In [10]:
features = features.to("cuda")
model = Model()
model.to("cuda")
model(features)

tensor([[-0.0236],
        [ 0.1802]], device='cuda:0', grad_fn=<AddmmBackward>)